apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
spec:
    replicas: 3
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: venzel/godeploy
                  resources:
                      limits:
                          memory: '32Mi'
                          cpu: '100m'

                  startupProbe:
                      httpGet:
                          path: /
                          port: 3000
                      periodSeconds: 10
                      failureThreshold: 10

                  readinessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      periodSeconds: 10
                      failureThreshold: 2
                      timeoutSeconds: 5

                  livenessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      periodSeconds: 10
                      failureThreshold: 3
                      timeoutSeconds: 5
                      successThreshold: 1

                  ports:
                      - containerPort: 3000
