// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"injections/product"
	"injections/usecases"
)

// Injectors from wire.go:

func NewCreateProductUseCase(db *sql.DB) *usecases.CreateProductUseCase {
	repository := product.NewProductRepository(db)
	createProductUseCase := usecases.NewCreateProductUseCase(repository)
	return createProductUseCase
}

func NewGetProductUseCase(db *sql.DB) *usecases.GetProductUseCase {
	repository := product.NewProductRepository(db)
	getProductUseCase := usecases.NewGetProductUseCase(repository)
	return getProductUseCase
}

// wire.go:

var productRepositoryDependency = wire.NewSet(product.NewProductRepository, wire.Bind(new(product.RepositoryInterface), new(*product.Repository)))
